=== interledger-deprecated/five-bells-notary/schemas/Case.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Case",
  "description": "A specific binary decision to be notarized",
  "type": "object",
  "properties": {
    "id": {
      "description": "Unique ID",
      "$ref": "Iri.json"
    },
    "execution_condition": {
      "description": "Cryptographic condition",
      "$ref": "Condition.json"
    },
    "expires_at": {
      "description": "The date when the case expires and will be rejected by the notary",
      "$ref": "Date.json"
    },
    "notaries": {
      "description": "Notaries (including this one) which are participating in this case",
      "type": "array",
      "items": {
        "$ref": "Iri.json"
      }
    },
    "notification_targets": {
      "description": "URIs Notary sends HTTP PUT request to, to notify the completion of this case",
      "type": "array",
      "items": {
        "$ref": "Iri.json"
      }
    },
    "state": {
      "description": "All cases start in the proposed state and are either executed or rejected",
      "enum": ["proposed", "executed", "rejected"]
    }
  },
  "required": ["execution_condition", "expires_at", "notaries", "notification_targets"],
  "additionalProperties": false
}

=== interledger-deprecated/five-bells-notary/test/data/basicCase.json
{
  "id": "http://localhost/cases/75159fb1-8ed2-4c92-9af7-0f48e2616f47",
  "execution_condition": {
    "type": "sha256",
    "digest": "50D858E0985ECC7F60418AAF0CC5AB587F42C2570A884095A9E8CCACD0F6545C"
  },
  "expires_at": "2015-11-19T20:27:12.299Z",
  "notaries": [
    "http://localhost"
  ],
  "notification_targets": ["https://localhost:3001/transfers/123"]
}

=== interledger-deprecated/five-bells-notary/test/data/caseInvalidNotificationTargets.json
{
  "id": "http://localhost/cases/75159fb1-8ed2-4c92-9af7-0f48e2616f47",
  "execution_condition": "cc:0:3:vmvf6B7EpFalN6RGDx9F4f4z0wtOIgsIdCmbgv06ceI:7",
  "expires_at": "2015-11-19T20:27:12.299Z",
  "notaries": [
    "http://localhost"
  ],
  "notification_targets": ["https://localhost:3001/transfers/123", "https://localhost:3001/transfers/123"]
}
